detector:
  ros__parameters:
    timer_period: 0.05
    nms_threshold: 0.35
    prob_threshold: 0.35
    target_size: 480
    weights: "best100ep1inp.ncnn" #best100ep1inp.ncnn best80ep.ncnn
    focal_length: 3.15
    width_side: 95.0
    width_front: 68.0
    K: 1.8
    Ti: 100.0
    Td: 0.0
    linearSpeed: 0.1
